[package]
name = "flg"
version = "0.2.0"
authors = ["Anish Kanthamneni <akneni@gmail.com>"]
edition = "2024"
description = "A linux profiling utility"
license = "MIT"

[dependencies]
clap = { version = "4", features = ["derive"] }
